#!/bin/sh

set -e -x

. /params
HOSTNAME_BASE=`echo "$HOSTNAME" | sed -e 's/\..*//'`

case `uname -m` in
x86_64)
	ARCH=amd64
	KARCH=amd64
	;;
i?86)
	ARCH=i386
	KARCH=686
	;;
esac

mkrawpart()
{
	mkfs.ext2 -L $2 $1
	mkdir -p /target/$2
	mount $1 /target/$2

	echo "LABEL=$2 $2 ext2 defaults 0 2" >> /fstab
}

mklvmpart()
{
	lvcreate -L $2 -n vg/$1
	mkfs.ext4 -O dir_index,extent -L $3 /dev/vg/$1
	mkdir -p /target/$3
	mount /dev/vg/$1 /target/$3

	if test $3 = /
	then
		PASS=1
	else
		PASS=2
	fi
	echo "/dev/mapper/vg-$1 $3 ext4 defaults 0 $PASS" >> /fstab
}

mkswappart()
{
	lvcreate -L $2 -n vg/$1
	mkswap /dev/vg/$1
	swapon /dev/vg/$1

	echo "/dev/mapper/vg-$1 none swap sw 0 0" >> /fstab
}

# Volume group
DISKS=
for i in /dev/sda2 /dev/sdb /dev/sdc
do
	if test -b $i
	then
		pvcreate -ffy $i
		DISKS="$DISKS $i"
	fi
done
vgcreate vg $DISKS

# Create partitions
echo 'proc /proc proc defaults 0 0' > /fstab
. /partitions

# Unpack base installation
debootstrap \
	--arch=$ARCH \
	squeeze \
	/target \
	http://64.50.233.100/debian

# Essential configuration files
install -m 444 /fstab /target/etc/fstab
cat > /target/etc/network/interfaces << EOF
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet dhcp
	dns-search $DNSDOMAINS
EOF
echo $HOSTNAME_BASE > /target/etc/hostname
sed -i "s/^127.0.0.1.*/127.0.0.1 $HOSTNAME $HOSTNAME_BASE localhost/" \
	/target/etc/hosts

cat > /target/etc/apt/sources.list.d/kumina.list << EOF
deb	http://debian.kumina.nl/debian	squeeze-kumina	main
EOF

mkdir /target/etc/apt/keys

# The kumina repository key
cat > /target/etc/apt/keys/056E8E56 << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEeUi5wRBADbhyh7Je9ZpByQ208EI8gXXYwOEhq6U5E9AmdUMQfyq64hFiot
K+G37s0dBJSIun/azR3chcstauUJWeLY2S1SzMbvggVh3K8J9aGMA8MvQSCNl8uJ
PaGxtGcpHOEhze69ZJ2nEzJfAn0PZhUxmRZAX0e662f/JHPnAUAFfrmk8wCgntPB
aJ1zXTCAcBNoGC/5WZLuOc0D/AjMsKcg+p6rhBb+R2zLTsZAySrt7O9NP5qld0RG
Xg5GgpnsTfQA801ta4QLAhV9PFSXFT8cNNj+RfKJWNm5Gb5ofD61dk2ziZi7V+1+
OZVYYgFk/45g5ClpDYiSYLeOYBAKw38Oiwf61vRsXDEfrjMl1Jxg/wy4CtmnCWMa
fO9TBAC/cPVU0EuGW5cA+GtJCpShyZiGBnlhsSFdvyOXa5rL69x3gHgBIZC5p+wi
+9M/7WnjoQv/ci/ILxY3ZSpnuFUWWSQ/ypxBy0XVD/JU/xxJRnPMwu5Uqu17jrbY
VwXJj4Ta3V/bi0+YfTLEd4v7dpi6U+4MnysMg7XUDqQ5rFiNw7RAS3VtaW5hIFBh
Y2thZ2UgQXJjaGl2ZSBBdXRvbWF0aWMgU2lnbmluZyBLZXkgPHN1cHBvcnRAa3Vt
aW5hLm5sPohmBBMRAgAmAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AFAk0kbJEF
CQsze3AACgkQ/uxb00mLkebj3wCfd6y4qXUO+x5j5ZwuYXuGsnpe44oAoIMhXnoq
4XtBf4GKixTXsBHkS98fiGYEExECACYFAkeUi5wCGwMFCQHNbQAGCwkIBwMCBBUC
CAMEFgIDAQIeAQIXgAAKCRD+7FvTSYuR5lNmAJ4tHHxzj66K1jlaVEk71kNWEv0m
7QCgmkyrjcicnixmv5w9zTaQK+ShUa25Ag0ER5SLthAIAO/gLHqfAqirItmAFJs4
vBX9EljQo8F5eaxDFbRzmlCFi+zJPZ1ZYbnZ/vdN8UxTa5XSNDiERxiv1cDmZ/u0
LApXdp+OTOn3G3wHjTzi4zbAMyqHQz+FbCPlslPPaif1WRb6UWfmQ5kXG97+N+JQ
Avx//jw0rhNIFnns2xg4G3Dn1PeiftKYOvLwtKSffFRXULueXwLW3gZdLN2hiZVZ
AuSl13ax9rqiy2jB4909YyZl6wro2dRcgOEE3kq6uoyD9wVL492dXRNZu7wmk5IX
yBlAHuAgRIih+rzFFof6r6+e3HjWM+VvFQ1WlzQexxrC616bvZbQtZOTpYgJi/cx
tu8AAwUH/1iJ6njNIe8jRK0JMeMRLydwwvgSNyrOoTCeKgCwrGuUBdp71HP1vL3Q
3umfrNzRN5DlObjJoLVq8bB/ePK0eBVh53qENiVJCqQRT7JHoN9tAqKAjpRfVOpq
lCKelrFfS3rZzuf7yBm4eBMx6MMlf0UDvycVTb4Pri5XExgZXgSdkrWlhmJA8iPR
Si+B7oVAJIJUmriVeH0Iod7StD/SHSmF3aqlJxaN5RF3zTA1LSihKTab/+qyXq1N
9m/nbQXpO4jdPnVnv3rj5xrp8/1itd5JOro/8MfhpJ6EdAMqdCan/Ce52/0QnumV
c9XPxKxlZ0G89b2L9vQutPgi6ZPOXFqITwQYEQIADwUCR5SLtgIbDAUJAc1tAAAK
CRD+7FvTSYuR5g+cAJsFPFyrfEN3gQyIfRaIAF/IDOttWACeMryROLvfnPYWSy9q
Fi5GYYVM9N4=
=h2Cw
-----END PGP PUBLIC KEY BLOCK-----
EOF

cat > /target/etc/apt/sources.list.d/squeeze-backports.list << EOF
deb	http://backports.debian.org/debian-backports	squeeze-backports	main contrib non-free
EOF

# The debian Backports key
cat > /target/etc/apt/keys/498B91E6 << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.0

mQGiBEeUi5wRBADbhyh7Je9ZpByQ208EI8gXXYwOEhq6U5E9AmdUMQfyq64hFiotK+G37s0d
BJSIun/azR3chcstauUJWeLY2S1SzMbvggVh3K8J9aGMA8MvQSCNl8uJPaGxtGcpHOEhze69
ZJ2nEzJfAn0PZhUxmRZAX0e662f/JHPnAUAFfrmk8wCgntPBaJ1zXTCAcBNoGC/5WZLuOc0D
/AjMsKcg+p6rhBb+R2zLTsZAySrt7O9NP5qld0RGXg5GgpnsTfQA801ta4QLAhV9PFSXFT8c
NNj+RfKJWNm5Gb5ofD61dk2ziZi7V+1+OZVYYgFk/45g5ClpDYiSYLeOYBAKw38Oiwf61vRs
XDEfrjMl1Jxg/wy4CtmnCWMafO9TBAC/cPVU0EuGW5cA+GtJCpShyZiGBnlhsSFdvyOXa5rL
69x3gHgBIZC5p+wi+9M/7WnjoQv/ci/ILxY3ZSpnuFUWWSQ/ypxBy0XVD/JU/xxJRnPMwu5U
qu17jrbYVwXJj4Ta3V/bi0+YfTLEd4v7dpi6U+4MnysMg7XUDqQ5rFiNw7RAS3VtaW5hIFBh
Y2thZ2UgQXJjaGl2ZSBBdXRvbWF0aWMgU2lnbmluZyBLZXkgPHN1cHBvcnRAa3VtaW5hLm5s
PohmBBMRAgAmAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AFAkl26KkFCQPDkIwACgkQ/uxb
00mLkeZTEQCeOB2d78FG1iw5yyLd9Nw7fksPtb8Ani2Rpef+Z6ubbP6J7fJiU5H8A0YhiGYE
ExECACYCGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAUCS123oQUJBapfdwAKCRD+7FvTSYuR
5r3TAJ9Kh41ezuclVI2pBZ4WWrvx8uKkMACggVNl/F5zKcUvlCDBMso5ItSpbyGIZgQTEQIA
JgIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheABQJNJGyRBQkLM3twAAoJEP7sW9NJi5Hm498A
n3esuKl1DvseY+WcLmF7hrJ6XuOKAKCDIV56KuF7QX+BiosU17AR5EvfH4hmBBMRAgAmBQJH
lIucAhsDBQkBzW0ABgsJCAcDAgQVAggDBBYCAwECHgECF4AACgkQ/uxb00mLkeZTZgCeLRx8
c4+uitY5WlRJO9ZDVhL9Ju0AoJpMq43InJ4sZr+cPc02kCvkoVGtuQINBEeUi7YQCADv4Cx6
nwKoqyLZgBSbOLwV/RJY0KPBeXmsQxW0c5pQhYvsyT2dWWG52f73TfFMU2uV0jQ4hEcYr9XA
5mf7tCwKV3afjkzp9xt8B4084uM2wDMqh0M/hWwj5bJTz2on9VkW+lFn5kOZFxve/jfiUAL8
f/48NK4TSBZ57NsYOBtw59T3on7SmDry8LSkn3xUV1C7nl8C1t4GXSzdoYmVWQLkpdd2sfa6
ostowePdPWMmZesK6NnUXIDhBN5KurqMg/cFS+PdnV0TWbu8JpOSF8gZQB7gIESIofq8xRaH
+q+vntx41jPlbxUNVpc0Hscawutem72W0LWTk6WICYv3MbbvAAMFB/9Yiep4zSHvI0StCTHj
ES8ncML4EjcqzqEwnioAsKxrlAXae9Rz9by90N7pn6zc0TeQ5Tm4yaC1avGwf3jytHgVYed6
hDYlSQqkEU+yR6DfbQKigI6UX1TqapQinpaxX0t62c7n+8gZuHgTMejDJX9FA78nFU2+D64u
VxMYGV4EnZK1pYZiQPIj0Uovge6FQCSCVJq4lXh9CKHe0rQ/0h0phd2qpScWjeURd80wNS0o
oSk2m//qsl6tTfZv520F6TuI3T51Z7964+ca6fP9YrXeSTq6P/DH4aSehHQDKnQmp/wnudv9
EJ7plXPVz8SsZWdBvPW9i/b0LrT4IumTzlxaiE8EGBECAA8FAkeUi7YCGwwFCQHNbQAACgkQ
/uxb00mLkeYPnACbBTxcq3xDd4EMiH0WiABfyAzrbVgAnjK8kTi735z2FksvahYuRmGFTPTe
=08XM
-----END PGP PUBLIC KEY BLOCK-----
EOF

cat > /target/etc/apt/preferences << EOF
Package: puppet
Pin: release a=squeeze-backports
Pin-Priority: 999

Package: puppet-common
Pin: release a=squeeze-backports
Pin-Priority: 999

Package: facter
Pin: version 1.5.9*
Pin-Priority: 999

Package: *
Pin: release a=squeeze-kumina
Pin-Priority: 999
EOF

# Install additional dependencies
mount -t devpts none /target/dev/pts
mount -t proc none /target/proc
chroot /target apt-get update
chroot /target apt-get -y install \
	linux-image-xen-$KARCH \
	lsb-release \
	lvm2 \
	openssh-server \
	puppet \
	resolvconf

# Install Puppet configuration
cat > /target/etc/puppet/puppet.conf << EOF
[main]
environment = $PUPPETENVIRONMENT
factpath = \$vardir/lib/facter
logdir = /var/log/puppet
pluginsync = true
rundir = /var/run/puppet
ssldir = /var/lib/puppet/ssl
templatedir = \$confdir/templates
vardir = /var/lib/puppet

[agent]
configtimeout = 1800
report = false
server = puppet1.kumina.nl
splay = false
EOF

cat > /target/etc/rc.local << EOF
#!/bin/sh

set -e

puppetd --verbose --no-daemonize --no-splay --onetime

if test -x /etc/rc.final
then
	# This node has a dedicated application
	/etc/rc.final
else
	# Just a generic system
	rm /etc/rc.local
fi
EOF
chmod +x /target/etc/rc.local
PUPDIR=/target/var/lib/puppet/ssl
mkdir -p $PUPDIR/ca/signed $PUPDIR/certs $PUPDIR/private_keys
cp /puppet.cert.pem $PUPDIR/ca/signed/$HOSTNAME.pem
cp /puppet.ca.pem $PUPDIR/certs/ca.pem
cp /puppet.privkey.pem $PUPDIR/private_keys/$HOSTNAME.pem

# Add SSH keys
if test -f /sshkeys
then
	mkdir -m 700 -p /target/root/.ssh
	cp /sshkeys /target/root/.ssh/authorized_keys
fi

# Patch up the boot loader, now that we have a kernel
cd /target/boot
mkdir -p boot/grub
cat > boot/grub/menu.lst << EOF
default 0
timeout 1

title Debian
	root	(hd0)
	kernel	/`echo vmlinu*` root=/dev/mapper/vg-root
	initrd	/`echo initrd*`
EOF
