#!/bin/sh

set -e -x

case $ARCH in
amd64)
	AKI=427d952b
	EC2ARCH=x86_64
	;;
i386)
	AKI=407d9529
	EC2ARCH=i386
	;;
esac

BUNDLEDIR=`mktemp -d /tmp/bundle.XXXXXX`

ec2-bundle-image -k $EC2_PRIVATE_KEY -c $EC2_CERT \
	-i install.rootfs.$ARCH --kernel aki-$AKI \
	-d $BUNDLEDIR -r $EC2ARCH --user $EC2_USER
ec2-upload-bundle -b nl.kumina.ami -d $BUNDLEDIR \
	-m $BUNDLEDIR/install.rootfs.$ARCH.manifest.xml \
	-a $EC2_ACCESS_KEY -s $EC2_SECRET_KEY
ec2-register nl.kumina.ami/install.rootfs.$ARCH.manifest.xml

rm -Rf $BUNDLEDIR
